export const BASE_RENDERER_EXPOSURE = 1.2
export const DEFAULT_EXPOSURE_EV100 = 15
export const DEFAULT_IBL_INTENSITY_MULTIPLIER = 1
export const DEFAULT_TORCH_CANDELA_MULTIPLIER = 1
export const MIN_IBL_INTENSITY_MULTIPLIER = 0
export const MAX_IBL_INTENSITY_MULTIPLIER = 4
export const MIN_TORCH_CANDELA_MULTIPLIER = 0
export const MAX_TORCH_CANDELA_MULTIPLIER = 4

export function getRendererExposure(ev100) {
  return BASE_RENDERER_EXPOSURE * (2 ** (DEFAULT_EXPOSURE_EV100 - ev100))
}
